[build]
  # We are deploying the pre-built web files directly.
  publish = "build/web"
  command = "" # [PRE-BUILT] No build command needed on Netlify

[[redirects]]
  # This ensures that Flutter's internal routing works correctly
  # on a single-page application (SPA).
  from = "/*"
  to = "/index.html"
  status = 200
